/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as EnDirectRouteImport } from './routes/en-direct'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ProspectionRouteImport } from './routes/prospection'
import { Route as TachesRouteImport } from './routes/taches'
import { Route as ApiAgentTickRouteImport } from './routes/api/agent/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDirectRoute = EnDirectRouteImport.update({
  id: '/en-direct',
  path: '/en-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionRoute = ProspectionRouteImport.update({
  id: '/prospection',
  path: '/prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const TachesRoute = TachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTickRoute = ApiAgentTickRouteImport.update({
  id: '/api/agent/tick',
  path: '/api/agent/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/en-direct': typeof EnDirectRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
  '/prospection': typeof ProspectionRoute
  '/taches': typeof TachesRoute
  '/api/agent/tick': typeof ApiAgentTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/en-direct': typeof EnDirectRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
  '/prospection': typeof ProspectionRoute
  '/taches': typeof TachesRoute
  '/api/agent/tick': typeof ApiAgentTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/en-direct': typeof EnDirectRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
  '/prospection': typeof ProspectionRoute
  '/taches': typeof TachesRoute
  '/api/agent/tick': typeof ApiAgentTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comptes'
    | '/en-direct'
    | '/messages'
    | '/parametres'
    | '/prospection'
    | '/taches'
    | '/api/agent/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comptes'
    | '/en-direct'
    | '/messages'
    | '/parametres'
    | '/prospection'
    | '/taches'
    | '/api/agent/tick'
  id:
    | '__root__'
    | '/'
    | '/comptes'
    | '/en-direct'
    | '/messages'
    | '/parametres'
    | '/prospection'
    | '/taches'
    | '/api/agent/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComptesRoute: typeof ComptesRoute
  EnDirectRoute: typeof EnDirectRoute
  MessagesRoute: typeof MessagesRoute
  ParametresRoute: typeof ParametresRoute
  ProspectionRoute: typeof ProspectionRoute
  TachesRoute: typeof TachesRoute
  ApiAgentTickRoute: typeof ApiAgentTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-direct': {
      id: '/en-direct'
      path: '/en-direct'
      fullPath: '/en-direct'
      preLoaderRoute: typeof EnDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection': {
      id: '/prospection'
      path: '/prospection'
      fullPath: '/prospection'
      preLoaderRoute: typeof ProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taches': {
      id: '/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof TachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/tick': {
      id: '/api/agent/tick'
      path: '/api/agent/tick'
      fullPath: '/api/agent/tick'
      preLoaderRoute: typeof ApiAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComptesRoute: ComptesRoute,
  EnDirectRoute: EnDirectRoute,
  MessagesRoute: MessagesRoute,
  ParametresRoute: ParametresRoute,
  ProspectionRoute: ProspectionRoute,
  TachesRoute: TachesRoute,
  ApiAgentTickRoute: ApiAgentTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
