/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as EnDirectRouteImport } from './routes/en-direct'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ProspectionRouteImport } from './routes/prospection'
import { Route as StrategieRouteImport } from './routes/strategie'
import { Route as SuppressionDonneesRouteImport } from './routes/suppression-donnees'
import { Route as TachesRouteImport } from './routes/taches'
import { Route as ApiAgentTickRouteImport } from './routes/api/agent/tick'
import { Route as ApiIaDiagnosticRouteImport } from './routes/api/ia/diagnostic'
import { Route as ApiInstagramRetourRouteImport } from './routes/api/instagram/retour'
import { Route as ApiMetaDiagnosticRouteImport } from './routes/api/meta/diagnostic'
import { Route as ApiMetaRetourRouteImport } from './routes/api/meta/retour'
import { Route as ApiVisuelsIdRouteImport } from './routes/api/visuels/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDirectRoute = EnDirectRouteImport.update({
  id: '/en-direct',
  path: '/en-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionRoute = ProspectionRouteImport.update({
  id: '/prospection',
  path: '/prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategieRoute = StrategieRouteImport.update({
  id: '/strategie',
  path: '/strategie',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppressionDonneesRoute = SuppressionDonneesRouteImport.update({
  id: '/suppression-donnees',
  path: '/suppression-donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const TachesRoute = TachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTickRoute = ApiAgentTickRouteImport.update({
  id: '/api/agent/tick',
  path: '/api/agent/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaDiagnosticRoute = ApiIaDiagnosticRouteImport.update({
  id: '/api/ia/diagnostic',
  path: '/api/ia/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramRetourRoute = ApiInstagramRetourRouteImport.update({
  id: '/api/instagram/retour',
  path: '/api/instagram/retour',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaDiagnosticRoute = ApiMetaDiagnosticRouteImport.update({
  id: '/api/meta/diagnostic',
  path: '/api/meta/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaRetourRoute = ApiMetaRetourRouteImport.update({
  id: '/api/meta/retour',
  path: '/api/meta/retour',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisuelsIdRoute = ApiVisuelsIdRouteImport.update({
  id: '/api/visuels/$id',
  path: '/api/visuels/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/en-direct': typeof EnDirectRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
  '/prospection': typeof ProspectionRoute
  '/strategie': typeof StrategieRoute
  '/suppression-donnees': typeof SuppressionDonneesRoute
  '/taches': typeof TachesRoute
  '/api/agent/tick': typeof ApiAgentTickRoute
  '/api/ia/diagnostic': typeof ApiIaDiagnosticRoute
  '/api/instagram/retour': typeof ApiInstagramRetourRoute
  '/api/meta/diagnostic': typeof ApiMetaDiagnosticRoute
  '/api/meta/retour': typeof ApiMetaRetourRoute
  '/api/visuels/$id': typeof ApiVisuelsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/en-direct': typeof EnDirectRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
  '/prospection': typeof ProspectionRoute
  '/strategie': typeof StrategieRoute
  '/suppression-donnees': typeof SuppressionDonneesRoute
  '/taches': typeof TachesRoute
  '/api/agent/tick': typeof ApiAgentTickRoute
  '/api/ia/diagnostic': typeof ApiIaDiagnosticRoute
  '/api/instagram/retour': typeof ApiInstagramRetourRoute
  '/api/meta/diagnostic': typeof ApiMetaDiagnosticRoute
  '/api/meta/retour': typeof ApiMetaRetourRoute
  '/api/visuels/$id': typeof ApiVisuelsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/en-direct': typeof EnDirectRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
  '/prospection': typeof ProspectionRoute
  '/strategie': typeof StrategieRoute
  '/suppression-donnees': typeof SuppressionDonneesRoute
  '/taches': typeof TachesRoute
  '/api/agent/tick': typeof ApiAgentTickRoute
  '/api/ia/diagnostic': typeof ApiIaDiagnosticRoute
  '/api/instagram/retour': typeof ApiInstagramRetourRoute
  '/api/meta/diagnostic': typeof ApiMetaDiagnosticRoute
  '/api/meta/retour': typeof ApiMetaRetourRoute
  '/api/visuels/$id': typeof ApiVisuelsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comptes'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/en-direct'
    | '/messages'
    | '/parametres'
    | '/prospection'
    | '/strategie'
    | '/suppression-donnees'
    | '/taches'
    | '/api/agent/tick'
    | '/api/ia/diagnostic'
    | '/api/instagram/retour'
    | '/api/meta/diagnostic'
    | '/api/meta/retour'
    | '/api/visuels/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comptes'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/en-direct'
    | '/messages'
    | '/parametres'
    | '/prospection'
    | '/strategie'
    | '/suppression-donnees'
    | '/taches'
    | '/api/agent/tick'
    | '/api/ia/diagnostic'
    | '/api/instagram/retour'
    | '/api/meta/diagnostic'
    | '/api/meta/retour'
    | '/api/visuels/$id'
  id:
    | '__root__'
    | '/'
    | '/comptes'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/en-direct'
    | '/messages'
    | '/parametres'
    | '/prospection'
    | '/strategie'
    | '/suppression-donnees'
    | '/taches'
    | '/api/agent/tick'
    | '/api/ia/diagnostic'
    | '/api/instagram/retour'
    | '/api/meta/diagnostic'
    | '/api/meta/retour'
    | '/api/visuels/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComptesRoute: typeof ComptesRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  EnDirectRoute: typeof EnDirectRoute
  MessagesRoute: typeof MessagesRoute
  ParametresRoute: typeof ParametresRoute
  ProspectionRoute: typeof ProspectionRoute
  StrategieRoute: typeof StrategieRoute
  SuppressionDonneesRoute: typeof SuppressionDonneesRoute
  TachesRoute: typeof TachesRoute
  ApiAgentTickRoute: typeof ApiAgentTickRoute
  ApiIaDiagnosticRoute: typeof ApiIaDiagnosticRoute
  ApiInstagramRetourRoute: typeof ApiInstagramRetourRoute
  ApiMetaDiagnosticRoute: typeof ApiMetaDiagnosticRoute
  ApiMetaRetourRoute: typeof ApiMetaRetourRoute
  ApiVisuelsIdRoute: typeof ApiVisuelsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-direct': {
      id: '/en-direct'
      path: '/en-direct'
      fullPath: '/en-direct'
      preLoaderRoute: typeof EnDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection': {
      id: '/prospection'
      path: '/prospection'
      fullPath: '/prospection'
      preLoaderRoute: typeof ProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategie': {
      id: '/strategie'
      path: '/strategie'
      fullPath: '/strategie'
      preLoaderRoute: typeof StrategieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppression-donnees': {
      id: '/suppression-donnees'
      path: '/suppression-donnees'
      fullPath: '/suppression-donnees'
      preLoaderRoute: typeof SuppressionDonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taches': {
      id: '/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof TachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/tick': {
      id: '/api/agent/tick'
      path: '/api/agent/tick'
      fullPath: '/api/agent/tick'
      preLoaderRoute: typeof ApiAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/diagnostic': {
      id: '/api/ia/diagnostic'
      path: '/api/ia/diagnostic'
      fullPath: '/api/ia/diagnostic'
      preLoaderRoute: typeof ApiIaDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/retour': {
      id: '/api/instagram/retour'
      path: '/api/instagram/retour'
      fullPath: '/api/instagram/retour'
      preLoaderRoute: typeof ApiInstagramRetourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/diagnostic': {
      id: '/api/meta/diagnostic'
      path: '/api/meta/diagnostic'
      fullPath: '/api/meta/diagnostic'
      preLoaderRoute: typeof ApiMetaDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/retour': {
      id: '/api/meta/retour'
      path: '/api/meta/retour'
      fullPath: '/api/meta/retour'
      preLoaderRoute: typeof ApiMetaRetourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visuels/$id': {
      id: '/api/visuels/$id'
      path: '/api/visuels/$id'
      fullPath: '/api/visuels/$id'
      preLoaderRoute: typeof ApiVisuelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComptesRoute: ComptesRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  EnDirectRoute: EnDirectRoute,
  MessagesRoute: MessagesRoute,
  ParametresRoute: ParametresRoute,
  ProspectionRoute: ProspectionRoute,
  StrategieRoute: StrategieRoute,
  SuppressionDonneesRoute: SuppressionDonneesRoute,
  TachesRoute: TachesRoute,
  ApiAgentTickRoute: ApiAgentTickRoute,
  ApiIaDiagnosticRoute: ApiIaDiagnosticRoute,
  ApiInstagramRetourRoute: ApiInstagramRetourRoute,
  ApiMetaDiagnosticRoute: ApiMetaDiagnosticRoute,
  ApiMetaRetourRoute: ApiMetaRetourRoute,
  ApiVisuelsIdRoute: ApiVisuelsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
